#!/bin/sh

echo "Running Code Reviewer..."

python3 reviewer.py scan sample_py.py

status=$?

if [ $status -ne 0 ]; then
  echo "❌ Commit blocked due to code issues."
  exit 1
fi

echo "✅ Code quality check passed."
exit 0
